/armor_detector:
  ros__parameters:
    subscribe_compressed: false

    min_lightness: 145

    light:
      max_angle: 40.0
      max_ratio: 0.4
      min_ratio: 0.1

    armor:
      max_angle: 35.0
      max_center_ratio: 1.6
      min_center_ratio: 0.4
      min_light_ratio: 0.6
      max_large_center_distance: 5.0
      min_large_center_distance: 3.2
      max_small_center_distance: 3.2
      min_small_center_distance: 0.8

    classifier:
      similarity_threshold: 0.7

/armor_processor:
  ros__parameters:
    target_frame: shooter_link

    tracker:
      max_match_distance: 0.2
      tracking_threshold: 5
      lost_threshold: 5