/**:
  ros__parameters:
    use_sensor_data_qos: false
    debug_mode: true

    detector:
      camera_name: 'camera'
      subscribe_compressed: false

      # Model 
      model_path: 'package://openvino_armor_detector/model/opt-1208-001.onnx'
      device_type: 'AUTO'
      confidence_threshold: 0.25
      top_k: 128
      nms_threshold: 0.3